[telegram]
token = "1984920177:AAFSmkaCsD8vnUYAbBpqmP7PncVZ_eyCaoY"
workers = 1
admins = [841986077]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 0
api_hash = ""

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = ""
